baseurl:
defaultContentLanguage: "en"
languageCode: "en-us"
enableEmoji: true
enableRobotsTXT: true
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme: "gokarna"
title: "Homealone Specifications"
paginate: 5

params:
  avatarAltText: "avatar"
  avatarSize: "size-s"
  avatarURL: "/images/avatar.webp"
  description: ""
  footer: "Deo gratis."
  showBackToTopButton: true
  accentColor: "#E2C290"
  contentTypeName: "content/posts"
  showMenuItems: 2
  socialIcons:
    - name: "twitter"
      url: "https://x.com/homealone_specs"
    - name: "github"
      url: "https://github.com/jan-domalaon"
    - name: "soundcloud"
      url: "https://soundcloud.com/skrumpti0uzz"
    - name: "itchdotio"
      url: "https://maritimes-gameworks.itch.io/"
    - name: "linktree"
      url: "https://linktr.ee/maybejan"
    - name: "email"
      url: "mailto:janbot_sec@protonmail.com"
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: false
  autoCover: true
  showLastUpdated: false

params.twitter:
  creator: ""
  site: ""

menu:
  main:
    - name: "Home"
      pre: "<span data-feather='home'></span>"
      url: "/"
      weight: 1
    - name: "Posts"
      pre: "<span data-feather='book'></span>"
      url: "/posts/"
      weight: 2
    - name: "Projects"
      pre: "<span data-feather='code'></span>"
      url: "/projects/"
      weight: 3
    - name: "Tags"
      pre: "<span data-feather='tag'></span>"
      url: "/tags/"
      weight: 4
    - identifier: "github"
      pre: "<span data-feather='github'></span>"
      url: "https://github.com/jan-domalaon"
      weight: 5
    - identifier: "buymeacoffee"
      pre: "<span data-feather='coffee'></span>"
      url: "https://ko-fi.com/jan_bot"
      weight: 6
    - identifier: "rss"
      pre: "<span data-feather='rss'></span>"
      url: "/index.xml"
      weight: 7

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 4
    ordered: false

minify:
  minifyOutput: true